### ISSUE TITLE
Enhancement: change the number of icons listed to be dynamic

### ISSUE THREAD

**Issue by RobTheFiveNine** [RobTheFiveNine/company-icons#3]
Currently, the number of icons served by the web app is hard coded in `src/index.html`. Ideally, this should be calculated when the icons JSON file is loaded, as it will be one less thing that needs to be updated alongside the JSON.

**Comment by luiserdef** [comment]
I can work on this

**Comment by RobTheFiveNine** [comment]
> I can work on this

I'm afraid someone just submitted a PR for this one! But thank you, nether the less 🎉

Happy Hacktoberfest!
