### ISSUE TITLE
Enhancement: Update dependencies

### ISSUE THREAD

**Issue by RobTheFiveNine** [RobTheFiveNine/company-icons#4]
Several of the runtime dependencies are currently outdated and should be updated.

Doing this update, however, is likely to cause issues with the latest major updates. After doing the updates (hint: `yarn upgrade-interactive` makes this easy), proper testing should be carried out to ensure everything still works (both by running the tests via `yarn run test` and a hands on test using `yarn run serve`)

**Note to Hacktoberfest participants:** although this may seem like an easy issue, it could in fact be quite challenging depending on what the updates could break. Please, do not just run the update command and send a PR; ensure your changes do work.

**Comment by asmitbm** [comment]
I would like to work on this!
